// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQZDvk0_TDdvZjNj1-uawpkHq9Q6-wiM',
    appId: '1:121039438158:web:dea74a699c1842d19d1e1f',
    messagingSenderId: '121039438158',
    projectId: 'matterseek-staging',
    authDomain: 'matterseek-staging.firebaseapp.com',
    storageBucket: 'matterseek-staging.firebasestorage.app',
    measurementId: 'G-7CQEET0YLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjo9s8dbX5B0oGmh1c9RpDU1vdPRzlIk',
    appId: '1:121039438158:android:7814818e60f1e02d9d1e1f',
    messagingSenderId: '121039438158',
    projectId: 'matterseek-staging',
    storageBucket: 'matterseek-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbh2A_97cPEvIzQ9w7bGDsJWW5MXS-Mxo',
    appId: '1:121039438158:ios:075c7f07fb109f5d9d1e1f',
    messagingSenderId: '121039438158',
    projectId: 'matterseek-staging',
    storageBucket: 'matterseek-staging.firebasestorage.app',
    iosBundleId: 'com.morganmind.app',
  );

}