class Tag {
  final String id;
  final String label;
  final String? userId;
  final bool autoGenerated;
  final bool isSystem;
  final DateTime? lastUsed;

  Tag({
    required this.id,
    required this.label,
    this.userId,
    this.autoGenerated = false,
    this.isSystem = false,
    this.lastUsed,
  });

  factory Tag.fromJson(Map<String, dynamic> json) {
    return Tag(
      id: json['id'],
      label: json['label'],
      userId: json['user_id'],
      autoGenerated: json['auto_generated'],
      isSystem: json['is_system'],
      lastUsed: DateTime.parse(json['last_used']),
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'label': label,
    'user_id': userId,
    'auto_generated': autoGenerated,
    'is_system': isSystem,
    'last_used': lastUsed?.toIso8601String(),
  };
} 